import { useEffect, useState } from "react";
import type { Plan } from "./types";

/**
 * The papers this server can actually build.
 *
 * ## Why this replaced a hardcoded list
 *
 * The four presets used to be a literal in `BlueprintScreen`, and they happened
 * to match the backend's four blueprints exactly — so it worked, and would have
 * gone on working right up until someone added or renamed a blueprint file. Then
 * it fails in the two worst ways at once: a real blueprint is invisible, and a
 * listed one 404s on click. A UI holding its own copy of server state is a bug
 * with a delay on it.
 *
 * ## Why the labels come from `/api/plan` and not from `/api/blueprints`
 *
 * `/api/blueprints` returns bare filename stems — no title, no marks, no
 * duration — and its shape is frozen in `API-CONTRACT.md` with two other
 * consumers (the static UI and a P5 test). Widening it to carry metadata would
 * break both for a cosmetic gain.
 *
 * `/api/plan` already returns exactly those fields, costs no quota, makes no
 * model call and runs the solver in 5–125 ms. So the ids come from the
 * authoritative list and every number on a card comes from the blueprint file
 * itself — nothing on this screen is a guess about what the server holds.
 */

export interface Preset {
  id: string;
  title: string;
  /** Null when the plan could not be read — the card still lists the blueprint. */
  marks: number | null;
  minutes: number | null;
}

export interface Blueprints {
  presets: Preset[];
  loading: boolean;
  error: string;
}

/** `ai_fundamentals_v1` → `Ai fundamentals v1`. Only used when a plan fails. */
function humanise(id: string): string {
  const words = id.replace(/[_-]+/g, " ").trim();
  return words.charAt(0).toUpperCase() + words.slice(1);
}

export function useBlueprints(): Blueprints {
  const [presets, setPresets] = useState<Preset[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let live = true;

    (async () => {
      try {
        const res = await fetch("/api/blueprints");
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const ids = (await res.json()) as string[];
        if (!live) return;

        // Listed immediately from the authoritative ids, then enriched. A blueprint
        // must never be missing from this screen just because its plan is slow.
        setPresets(ids.map((id) => ({ id, title: humanise(id), marks: null, minutes: null })));
        setLoading(false);

        // In parallel, and each failure is contained: one unreadable blueprint
        // file leaves its own card thin rather than emptying the screen.
        const detailed = await Promise.all(
          ids.map(async (id): Promise<Preset> => {
            try {
              const r = await fetch("/api/plan", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ blueprint_id: id }),
              });
              if (!r.ok) throw new Error(String(r.status));
              const plan = (await r.json()) as Plan;
              return {
                id,
                title: plan.title,
                marks: plan.total_marks,
                minutes: plan.duration_minutes,
              };
            } catch {
              return { id, title: humanise(id), marks: null, minutes: null };
            }
          }),
        );
        // Cheapest first, so the default selection is the smallest paper.
        // The ids sort alphabetically, which put a 100-mark authored final at
        // the top and made it what a first-time student generated by default -
        // five times the spend of the quiz that used to be there. Ordering by
        // marks is derived from the blueprints themselves, not a curated list
        // that would drift the same way the hardcoded presets did.
        // Blueprints whose plan failed have no marks; they sort last.
        const byCost = [...detailed].sort(
          (a, b) => (a.marks ?? Infinity) - (b.marks ?? Infinity),
        );
        if (live) setPresets(byCost);
      } catch (e) {
        if (!live) return;
        setError(e instanceof Error ? e.message : String(e));
        setLoading(false);
      }
    })();

    return () => {
      live = false;
    };
  }, []);

  return { presets, loading, error };
}
